baseDir: "."
codebase: "/code"
soloCBlen: 16
soloCBstart: 1
soloUMIstart: 17
soloUMIlen: 12
dumpT: 12
soloStrand: "Forward"
threads: 16
ram: 64
alignment: "STAR"
technology: "10XV2"
virus_database: "viruSITE"
pseudoBAM: ""
soloMultiMappers: "EM"
soloFeatures: "GeneFull"
outSAMtype: "BAM SortedByCoordinate"
soloInputSAMattrBarcodeSeq: "CR UR"
soloInputSAMattrBarcodeQual: "-"
barcodes_whitelist: "3M-february-2018.txt"
reads:
- "SRR12570202"
- "SRR12570203"
- "SRR12570204"