soloStrand: "Forward"
alignment: "STAR"
technology: "10XV2"
virus_database: "viruSITE"
soloMultiMappers: "EM"
soloFeatures: "GeneFull"
reads:
- "SRR11680226"
- "SRR12404292"
- "SRR12594385"
- "SRR13094674"
- "SRR12570858"
- "SRR13711616"
- "SRR11934378"
- "SRR14163131"
