soloStrand: "Reverse"
alignment: "STAR"
technology: "10XV2"
virus_database: "viruSITE"
soloMultiMappers: "EM"
soloFeatures: "GeneFull"
reads:
- "SRR11537946"
- "SRR11537947"
# - "SRR11537948"
# - "SRR11181954"
# - "SRR11181955"
# - "SRR11181957"